routes/logout.py
# Importar flask y otros metodos
from flask import Blueprint, render_template, session, redirect, url_for, make_response
from functools import wraps

logout = Blueprint("logout", __name__)

@logout.route('/salir')
def verificar():
    # Elimina la información de inicio de sesión de la sesión
    if 'rol' in session:
        del session['rol']
    if 'idUsuarioRolFK' in session:
        del session['idUsuarioRolFK']
    session['cerrado'] = True  # Marca al usuario como "cerrado"
    
    # Redirige al usuario a la página de inicio
    response = make_response(redirect(url_for('login.home')))
    
    # Configura las directivas de control de caché
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    
    return response

#Cerrar sesion
def cerrarSesion(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if 'rol' not in session:
            return redirect(url_for('login.iniciarSesion'))
        return func(*args, **kwargs)  # Llama a la función original
    return wrapper

routes/menuAdministrador.py
# Importar flask y otros metodos
from flask import Blueprint, render_template

#Importar el decorador
from .validateRol import usuarioAdminRequired
from .logout import cerrarSesion

menuAdministrador = Blueprint("menuAdmin", __name__)

@menuAdministrador.route("/menuAdmin")
@usuarioAdminRequired
@cerrarSesion
def menuAdmin():
    return render_template("Administrador/menuAdministrador.html")

templates/Administrador/menuAdministrador.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/index/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{url_for('static',filename='css/administrador.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/administrador2.css')}}">

</head>
<body> 
    <div class="logo-container">
        <img class="logo" src="{{url_for('static',filename='img/index/logo2.jpg')}}" alt="">
    </div>
    <div style="text-align: center;"><h1>Bienvenido Administrador</h1></div>
      <header>
        <nav>
            <div style="text-align: center;">
        </div>
            <ul class="menu-horizontal">
                <li>
                    <a href="/registrarPlato">Registrar Plato</a>
                <li>
                    <a href="/listarPlato">Consultar plato</a>
                </li>
                <li>
                    <a href="/registrarIngrediente"> Registrar Ingrediente</a>
                </li>
                <li>
                    <a href="/listarIngrediente"> Consultar Ingrediente</a>
                </li>
                <li>
                    <a href="/listarComandas"> Ver comandas</a>
                </li>
                <li><a href="{{(url_for('logout.verificar'))}}">Cerrar Sesion</a></li>
            </ul>
        </nav>
        <section class="textos-header">
           
        </section>
     
    </header>

	<section class="zona1"></section>
	<section>
        <br>	
	</section>
	

	<script type="text/javascript">
		window.addEventListener("scroll", function(){
			var header = document.querySelector("header");
			header.classList.toggle("abajo",window.scrollY>0);})
	</script>
    <script>
        window.onpageshow = function(event) {
            if (event.persisted) {
                window.location.reload();
            }
        };
    </script>
</body>
</html>