routes/ingredients.py
# Importar flask y otros metodos
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify

# Importar mi modelo
from models.Modelos import Ingrediente

# Conexion a la bd
from utils.db import db

#Importar el decorador
from .validateRol import usuarioAdminRequired
from .logout import cerrarSesion
from sqlalchemy.exc import IntegrityError

ingredients = Blueprint("ingredients", __name__)

@ingredients.route("/listarIngrediente")
@usuarioAdminRequired
@cerrarSesion
def consultarIngrediente():
    ingredients = Ingrediente.query.all()
    return render_template("ingrediente/Consultar_Ingrediente.html", ingredients=ingredients)


@ingredients.route("/registrarIngrediente")
@usuarioAdminRequired
@cerrarSesion
def capturarIngrediente():
    return render_template("ingrediente/RegistrarIngrediente.html")


@ingredients.route("/registrarIngredient", methods=["POST"])
@usuarioAdminRequired
@cerrarSesion
def registrarIngrediente():
    nombre = request.form["nombre"]
    descripcion = request.form["descripcion"]
    tipoSabor = request.form["tipoSabor"]
    categoria = request.form["categoria"]

    estado = "Activo" 

    nuevoIngrediente = Ingrediente(nombre, descripcion, tipoSabor, categoria, estado)

    db.session.add(nuevoIngrediente)
    db.session.commit()

    flash("El ingrediente se registró correctamente", "success")

    return redirect(url_for("ingredients.consultarIngrediente"))


@ingredients.route("/actualizarIngrediente/<codigoIngrediente>", methods=["POST", "GET"])
@usuarioAdminRequired
@cerrarSesion
def actualizarIngrediente(codigoIngrediente):

    ingrediente = Ingrediente.query.get(codigoIngrediente)

    if request.method == "POST":
        ingrediente.nombreIngrediente = request.form["nombre"]
        ingrediente.descripcionIngrediente = request.form["descripcion"]
        ingrediente.tipoSaborIngrediente = request.form["tipoSabor"]
        ingrediente.categoriaIngrediente = request.form["categoria"]

        db.session.commit()
        
        flash("El ingrediente se actualizó correctamente", "success")
                
        return redirect(url_for("ingredients.consultarIngrediente"))

    return render_template("ingrediente/ActualizarIngrediente.html", ingrediente=ingrediente)


@ingredients.route("/eliminarIngrediente/<codigoIngrediente>", methods=['POST'])
@usuarioAdminRequired
@cerrarSesion
def eliminarIngrediente(codigoIngrediente):
    try:
        ingredient = Ingrediente.query.get(codigoIngrediente)

        if ingredient:
            # Actualiza el campo 'estado' en lugar de eliminar físicamente
            ingredient.estadoIngrediente = ("Inactivo")
            db.session.commit()
            flash("El ingrediente se eliminó correctamente", "success")
            return jsonify({'message': 'Plato eliminado con éxito'})
        else:
            flash("No se pudo encontrar el ingrediente a eliminar", "error")
            return jsonify({'message': 'Error al eliminar el plato'})
    except IntegrityError as e:
        # Si hay una violación de la clave externa, maneja el error
        db.session.rollback()
        flash(f"No se puede eliminar el plato debido a restricciones de integridad referencial: {str(e)}", "error")
        return jsonify({'message': f'Error al eliminar el plato debido a restricciones de integridad referencial: {str(e)}'})

        

templates/ingrediente/ActualizarIngrediente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Ingrediente</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/index/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="login-page">
        <div class="form">
          <img  src="{{url_for('static',filename='img/index/logo2.jpg')}} "  >
          <form action="/actualizarIngrediente/{{ ingrediente.codigoIngrediente }}" method="POST" class="login-form">
            <br><br>
            <label for="">Nombre del ingrediente</label>
            <input type="text" name="nombre" value="{{ ingrediente.nombreIngrediente }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Descripción del plato</label>
            <input type="text" name="descripcion" value="{{ ingrediente.descripcionIngrediente }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{7,}" required/>
            <label for="">Tipo sabor del ingrediente</label>
            <select class="input-contenedor" name="tipoSabor" required>
              <option value="{{ ingrediente.tipoSaborIngrediente }}">{{ ingrediente.tipoSaborIngrediente }}</option>
              <option value="Dulce">Dulce</option>
              <option value="Salado">Salado</option>
              <option value="Amargo">Amargo</option>
              <option value="Ácido">Ácido</option>
              <option value="Umami">Umami</option>
            </select>
            <label for="">Categoría del ingrediente</label>
            <select class="input-contenedor" name="categoria" required>
              <option value="{{ ingrediente.categoriaIngrediente }}">{{ ingrediente.categoriaIngrediente }}</option>
              <option value="Granos">Granos</option>
              <option value="Verduras">Verduras</option>
              <option value="Frutas">Frutas</option>
              <option value="Lácteos">Lácteos</option>
              <option value="Proteínas">Proteínas</option>
            </select>
            <br>
            <button>Actualizar</button>
          </form>
        </div>
      </div>
</body>
</html>

templates/ingrediente/Consultar_Ingrediente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static',filename='img/index/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/estilos.css')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <title>Consultar Ingrediente</title>
</head>
<body>
  <div class="pagi">
    <ul>
        <li class="scroll-to-section"><a href="/menuAdmin" class="activate">volver</a></li>
    </ul>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <ul>
        {% for category, message in messages %}
          <li class="alert alert-{{ category }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}

    <table>
      <div class="logo-container">
        <img class="logo" src="{{url_for('static',filename='img/index/logo2.jpg')}} ">
      </div>
        <thead>
            <tr>
              <th>Código </th>
              <th>Nombre</th>
              <th>Descripción</th>
              <th>Tipo Sabor</th>
              <th>Categoria</th>
              <th></th>
              <th></th>
            </tr>
        </thead>
        {% for ingredient in ingredients %}
          {% if ingredient.estadoIngrediente == "Activo" %}
            <tbody>
                <tr>
                    <td>{{ ingredient.codigoIngrediente }}</td>
                    <td>{{ ingredient.nombreIngrediente }}</td>
                    <td>{{ ingredient.descripcionIngrediente }}</td>
                    <td>{{ ingredient.tipoSaborIngrediente }}</td>
                    <td>{{ ingredient.categoriaIngrediente }}</td>
                    <td>
                      <a href="{{ url_for('ingredients.actualizarIngrediente', codigoIngrediente=ingredient.codigoIngrediente) }}" class="boton">Actualizar</a>
                    </td>
                    <td>
                      <button class="boton boton-rojo" data-toggle="modal" data-target="#confirmacionModal-{{ ingredient.codigoIngrediente }}">Eliminar</button>
                    </td> 
                </tr>
            </tbody>
          {% endif %}
            <!-- Modal de confirmación -->
            <div class="modal" tabindex="-1" role="dialog" id="confirmacionModal-{{ ingredient.codigoIngrediente }}">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Confirmar Eliminación</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <p>¿Estás seguro de que deseas eliminar el ingrediente "{{ ingredient.nombreIngrediente }}"?</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-danger" onclick="eliminarIngrediente('{{ ingredient.codigoIngrediente }}')">Sí, eliminar</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
    </table>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
    function eliminarIngrediente(codigoIngrediente) {
        // Hacer una solicitud AJAX para eliminar el plato
        $.ajax({
            type: 'POST',
            url: '/eliminarIngrediente/' + codigoIngrediente,
            success: function (response) {
                alert('Ingrediente eliminado con éxito');
                location.reload();  // Recargar la página después de la eliminación
            },
            error: function (xhr, status, error) {
                console.error('Error al eliminar el plato:', status, error);
                alert('Error al eliminar el ingrediente. Consulta la consola para más detalles.');
            }
        });
    }
  </script>
</body>
</html>

templates/ingrediente/RegistrarIngrediente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Ingrediente</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/index/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="pagi">
    <ul>
        <li class="scroll-to-section"><a href="/menuAdmin" class="activate">volver</a></li>
    </ul>
  </div>
    <div class="login-page">
        <div class="form">
          <form action="/registrarIngredient" method="POST" class="login-form">
            <img src="{{url_for('static',filename='img/index/logo2.jpg')}} "  >
            <br><br>
            <label for="">Nombre del ingrediente</label>
            <input type="text" name="nombre" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Descripción del ingrediente</label>
            <input type="text" name="descripcion" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{7,}" required/>
            <label for="">Tipo sabor del ingrediente</label>
            <select class="input-contenedor" name="tipoSabor" required>
              <option value=""></option>
              <option value="Dulce">Dulce</option>
              <option value="Salado">Salado</option>
              <option value="Amargo">Amargo</option>
              <option value="Ácido">Ácido</option>
              <option value="Umami">Umami</option>
            </select>
            <label for="">Categoría del ingrediente</label>
            <select class="input-contenedor" name="categoria" required>
              <option value=""></option>
              <option value="Granos">Granos</option>
              <option value="Granos">Salsas</option>
              <option value="Granos">Harinas</option>
              <option value="Verduras">Verduras</option>
              <option value="Frutas">Frutas</option>
              <option value="Lácteos">Lácteos</option>
              <option value="Proteínas">Proteínas</option>
            </select>
            <br>
            <button>Registrar</button>
          </form>
        </div>
      </div>
</body>
</html>