routes/plates.py
# Importar flask y otros metodos
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify

# Importar mi modelo
from models.Modelos import Plato

# Conexion a la bd
from utils.db import db

#Importar el decorador
from .validateRol import usuarioAdminRequired
from .logout import cerrarSesion
from sqlalchemy.exc import IntegrityError

plates = Blueprint("plates", __name__)

@plates.route("/listarPlato")
@usuarioAdminRequired
@cerrarSesion
def consultarPlato():
    plates = Plato.query.all()
    return render_template("plato/Consultar_Plato.html", plates=plates)


@plates.route("/registrarPlato")
@usuarioAdminRequired
@cerrarSesion
def capturarPlato():
    return render_template("plato/RegistrarPlato.html")

@plates.route("/registrarPlate", methods=["POST"])
@usuarioAdminRequired
@cerrarSesion
def registrarPlato():
    nombre = request.form.get("nombre")
    descripcion = request.form.get("descripcion")
    precio = request.form.get("precio")
    
    estado = "Activo" 

    nuevoPlato = Plato(nombre, descripcion, precio, estado)

    db.session.add(nuevoPlato)
    db.session.commit()
    
    flash("El plato se registró correctamente", "success")

    return redirect(url_for("plates.consultarPlato"))


@plates.route("/actualizarPlato/<codigoPlato>", methods=["POST", "GET"])
@usuarioAdminRequired
@cerrarSesion
def actualizarPlato(codigoPlato):

    plate = Plato.query.get(codigoPlato)

    if request.method == "POST":
        plate.nombrePlato = request.form["nombre"]
        plate.descripcionPlato = request.form["descripcion"]
        plate.precioPlato = request.form["precio"]

        db.session.commit()
        
        flash("El ingrediente se actualizó correctamente", "success")
        
        return redirect(url_for("plates.consultarPlato"))

    return render_template("plato/ActualizarPlato.html", plate=plate)


@plates.route("/eliminarPlato/<int:codigoPlato>", methods=['POST'])
@usuarioAdminRequired
@cerrarSesion
def eliminarPlato(codigoPlato):
    try:
        plate = Plato.query.get(codigoPlato)

        if plate:
            # Actualiza el campo 'estado' en lugar de eliminar físicamente
            plate.estadoPlato = ("Inactivo")
            db.session.commit()
            flash("El plato se eliminó correctamente", "success")
            return jsonify({'message': 'Plato eliminado con éxito'})
        else:
            flash("No se pudo encontrar el plato a eliminar", "error")
            return jsonify({'message': 'Error al eliminar el plato'})
    except IntegrityError as e:
        # Si hay una violación de la clave externa, maneja el error
        db.session.rollback()
        flash(f"No se puede eliminar el plato debido a restricciones de integridad referencial: {str(e)}", "error")
        return jsonify({'message': f'Error al eliminar el plato debido a restricciones de integridad referencial: {str(e)}'})


@plates.route("/buscarPlato")
@usuarioAdminRequired
@cerrarSesion
def buscar_platos():
    search_term = request.args.get("nombre").lower()
    resultados = Plato.query.filter(Plato.nombrePlato.ilike(f"%{search_term}%")).all()
    resultados = [{"id": plato.id, "nombrePlato": plato.nombrePlato} for plato in resultados]
    return jsonify(resultados)

templates/plato/ActualizarPlato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Plato</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/index/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="login-page">
        <div class="form">
          <form action="/actualizarPlato/{{ plate.codigoPlato }}" method="POST" class="login-form">
            <img src="{{url_for('static',filename='img/index/logo2.jpg')}} "  >
            <!--<img src="../../Assets/imagene/img/logo2.jpg" height="150px" width="150px" >-->
            <br><br>
            <label for="">Nombre del plato</label>
            <input type="text" name="nombre" value="{{ plate.nombrePlato }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}"  required/>
            <label for="">Descripción del plato</label>
            <input type="text" name="descripcion" value="{{ plate.descripcionPlato }}" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{10,}" required/>
            <label for="">Precio del plato</label>
            <input type="number" name="precio" value="{{ plate.precioPlato }}" min="5000" step="1" required/>
            <br>
            <button>Actualizar</button>
          </form>
        </div>
      </div>
</body>
</html>

templates/plato/Consultar_Plato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static',filename='img/index/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/estilos.css')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <title>Consultar Plato</title>
</head>
<body>
  <div class="pagi">
    <ul>
        <li class="scroll-to-section"><a href="/menuAdmin" class="activate">volver</a></li>
    </ul>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <ul>
        {% for category, message in messages %}
          <li class="alert alert-{{ category }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
  
  <table>
    <div class="logo-container">
      <img class="logo" src="{{url_for('static',filename='img/index/logo2.jpg')}} ">
    </div>
    <thead>
        <tr>
          <th>Código </th>
          <th>Nombre</th>
          <th>Descripción</th>
          <th>Precio</th>
          <th></th>
          <th></th>
        </tr>
    </thead>
    {% for plate in plates %}
      {% if plate.estadoPlato == "Activo" %}
        <tbody>
            <tr>
                <td>{{ plate.codigoPlato }}</td>
                <td>{{ plate.nombrePlato }}</td>
                <td>{{ plate.descripcionPlato }}</td>
                <td>{{ plate.precioPlato }}</td>
                <td>
                  <a href="{{ url_for('plates.actualizarPlato', codigoPlato=plate.codigoPlato) }}" class="boton">Actualizar</a>
                </td>
                <td>
                  <button class="boton boton-rojo" data-toggle="modal" data-target="#confirmacionModal-{{ plate.codigoPlato }}">Eliminar</button>
                </td> 
            </tr>
        </tbody>
      {% endif %}
      <!-- Modal de confirmación -->
      <div class="modal" tabindex="-1" role="dialog" id="confirmacionModal-{{ plate.codigoPlato }}">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Confirmar Eliminación</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>¿Estás seguro de que deseas eliminar el plato "{{ plate.nombrePlato }}"?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" onclick="eliminarPlato('{{ plate.codigoPlato }}')">Sí, eliminar</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </table>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>
  function eliminarPlato(codigoPlato) {
      // Hacer una solicitud AJAX para eliminar el plato
      $.ajax({
          type: 'POST',
          url: '/eliminarPlato/' + codigoPlato,
          success: function (response) {
              alert('Plato eliminado con éxito');
              location.reload();  // Recargar la página después de la eliminación
          },
          error: function (xhr, status, error) {
              console.error('Error al eliminar el plato:', status, error);
              alert('Error al eliminar el plato. Consulta la consola para más detalles.');
          }
      });
  }
</script>
</body>
</html>

templates/plato/RegistrarPlato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Plato</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='img/index/logo2.jpg')}}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/login.css')}}">
</head>
  <body>
    <div class="pagi">
      <ul>
          <li class="scroll-to-section"><a href="/menuAdmin" class="activate">volver</a></li>
      </ul>
    </div>
    <div class="login-page">
        <div class="form">
          <form id="registrarPlato" action="/registrarPlate" method="POST" class="login-form">
            <img src="{{url_for('static',filename='img/index/logo2.jpg')}} "  >
            <br><br>
            <label for="">Nombre del plato</label>
            <input type="text" name="nombre" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Descripción del plato</label>
            <input type="text" name="descripcion" pattern="[A-Za-zÁÉÍÓÚáéíóúñÑ\s]{5,}" required/>
            <label for="">Precio del plato</label>
            <input type="number" name="precio" min="5000" step="1" required/>
            <br>
            <button type="submit">Registrar</button>
          </form>
        </div>
      </div>  
  </body>
</html>